name: Test Pipeline

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: [self-hosted, test]

    steps:
      - name: Update test folder
        shell: powershell
        run: |
          git -C "C:\VSC\CD\test\task" fetch origin
          git -C "C:\VSC\CD\test\task" checkout test
          git -C "C:\VSC\CD\test\task" reset --hard origin/test

      - name: Check Python syntax
        shell: powershell
        run: |
          cd "C:\VSC\CD\test\task"
          python -m py_compile hello.py

      - name: Run and check program
        shell: powershell
        run: |
          cd "C:\VSC\CD\test\task"

          $output = python hello.py

          if ($LASTEXITCODE -ne 0) {
              Write-Error "Program crashed!"
              exit 1
          }

          if ($output -ne "Hello World") {
              Write-Error "Wrong output: $output"
              exit 1
          }

          Write-Host "Everything works correctly!"